# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libmagick++-dev
      - xclip
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install(); getwd(); covrpage::covrpage(vignette = TRUE)'
  - Rscript -e 'pkgdown::build_site()'

r_github_packages: 
  - yonicd/covrpage@2fd720e
  - r-lib/pkgdown

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master