# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libmagick++-dev
      - xclip

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install(); covrpage::covrpage(preview=FALSE,update_badge = FALSE,vignette = TRUE)'
  - Rscript -e 'pkgdown::build_site()'

r_github_packages:
  - yonicd/covrpage
  - r-lib/pkgdown
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: covrpage_publish